app/ripper-ui/config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: 'jobs#index'
  resources :jobs
  get 'jobs/status/:id' => 'jobs#status'
  get 'jobs/download/:id' => 'jobs#download'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/ripper-ui/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/ripper-ui/app/models/job.rb
class Job < ApplicationRecord

	has_many :profiles

	def percent
		(ripped_media.to_f / total_media.to_f) * 100
	end
end

app/ripper-ui/app/models/profile.rb
class Profile < ApplicationRecord

belongs_to :job

end

app/ripper-ui/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/ripper-ui/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :status, :download]

  def download
    path = "tmp/downloads/"
    folder_name = @job.created_at.strftime("%Y%m%d%H%M")
    folder = path + folder_name
    zipfile_name = folder + "/#{folder_name}.zip"

    #If zip file not created, create zip file else downlaoad created
    if not File.file?(zipfile_name)
      require 'zip'
      files = []

      @job.profiles.each do |p|
        files << p.username + ".json"
      end

      Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
        files.each do |filename|
          zipfile.add(filename, folder + '/' + filename)
        end
      end
    end

    send_file(File.open zipfile_name)

  end

  def status
    @percent = @job.percent
    @percent = 1 if @percent <= 1
    @percent = 100 if @job.done? or @percent > 100
    @percent = @percent.to_i
    render layout: false
  end

  def update
    @job.update_attribute(:done, true)
    redirect_to jobs_url
  end

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.where(done: true).order(id: "desc")
    @job = Job.where(done: false).last
    @job = Job.new if @job.nil?
  end


  # POST /jobs
  # POST /jobs.json
  def create

    return redirect_to action: :index if params[:input_file].blank? && params[:job]["input"].blank?

    max = 50
    @job = Job.new(job_params)

    profiles_input = []

    profiles_input << params[:job]["input"] if params[:input_file].blank?

    if not params[:input_file].blank?
      file = params[:input_file]
      json = file.read
      json = JSON.parse json
      json.each do |profile|
        profiles_input << [profile[0], profile[1]]
      end
    end

    has_location = (params[:has_location] == "on")

    total_media = 0
    profiles_input.each do |p|
      profile = Profile.new
      
      begin
        if p[0].is_a? Integer
          instagram_profile = Instagram::Location.new p[0].to_i
          profile.is_location = true
        else
          instagram_profile = Instagram::Profile.new p[0].to_s
        end
        @job.total_profiles += 1
        @job.total_media += instagram_profile.media_count
        profile.username = p[0].to_s
        profile.from_date = p[1].to_i
        @job.profiles << profile
      rescue
        puts "[ERROR] Error to try to find profile <#{p[0]}>!"
      end

    end

    @job.total_media = max * @job.profiles.size unless max.nil?

    respond_to do |format|
      if @job.save
        RipperWorker.perform_async(@job.id, params[:media_type], has_location, max)
        format.html { redirect_to action: index, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :index }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:input)
    end
end

app/ripper-ui/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:username, :ripped)
    end
end

app/ripper-ui/app/helpers/application_helper.rb
module ApplicationHelper
end

app/ripper-ui/app/helpers/jobs_helper.rb
module JobsHelper
end

app/ripper-ui/app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/ripper-ui/app/views/jobs/_form.html.erb
<h3 class="bg-info">This trial version fetch at max 50 posts per profile.</h3>

<div class="form-group form-group-lg">
  <div class="col-sm-14">
  <%= form_for(job, :html => { :multipart => true }) do |f| %>
    <% if job.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>
  
        <ul>
          <% job.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <label class="radio-inline"><input type="radio" checked="checked" name="media_type" value="all">All posts</label>
    <label class="radio-inline"><input type="radio" name="media_type" value="photos">Only Photos</label>
    <label class="radio-inline"><input type="radio" name="media_type" value="videos">Only Videos</label>
    |
    <label class="checkbox-inline"><input type="checkbox" name="has_location" checked="checked">Only has location</label>

    <%= f.text_field(:input, class: "form-control input-lg", placeholder: "User profile or Location ID.") %>
    
    <div align="center"><h3>OR</h3></div>
  
    <%= file_field_tag(:input_file, class: "form-control input-lg", placeholder: "User profile or Location ID.", "data-toggle" => "tooltip",  "data-placement" => "bottom", title: "Upload PROFILES OR LOCATIONS Json file to fetch. JSON file must have an Array structure such as: ['profile1', 'profile2'] for Profile OR integer Locations IDs for Locations such as: [123456, 654321]") %>
  
    </br>
  
    <div class="actions">
      <%= f.submit "Fetch!", class: "form-control btn-info" %>
    </div>
  <% end %>
</div>
<script>
$(document).ready(function(){
    //$('[data-toggle="tooltip"]').tooltip();
    $('[data-toggle="tooltip"]').tooltip();
});

</script>

app/ripper-ui/app/views/jobs/_list.html.erb
<div class="container">
<h3>History</h3>
	<table class="table">
		<thead>
			<tr>
				<th>Created At</th>
				<th>Profile Type</th>
				<th>Input</th>
				<th>Profiles</th>
				<th>Total Media</th>
				<th>Ripped Media</th>
				<th>%</th>
			</tr>
		</thead>
		<tbody>
			<% jobs.each_with_index do |job, idx| %>
				<% if job.percent < 100 %>
					<tr class="danger">
				<% else %>
					<tr class="<%= idx == 0 ? 'warning' : 'success' %>">
				<% end %>
					<td><%= job.created_at.strftime("%Y-%m-%d %H:%M") %></td>
					<td style="font-size:30px; <%= "color: blue" if job.profiles.first.is_location?%>" align="center"><span class="glyphicon <%= job.profiles.first.is_location? ? "glyphicon-map-marker" : "glyphicon-user" %>"></span></td>
					<td><%= job.input %></td>
					<td><%= job.profiles.size %></td>
					<td><%= job.total_media %></td>
					<td><%= job.ripped_media %></td>
					<td><%= job.percent %>%</td>
					<td>
						<%=
							button_to 'Download', {action: 'download', id: job.id}, method: :get, class: 'form-control btn-info', form: {target: '_blank'}
						%>
					</td>
					<td>
						<%=
							button_to 'Delete', job, method: :delete,
							data: { confirm: 'Are you sure?' },
							class: 'form-control btn-danger'
						%>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
  

</div>

app/ripper-ui/app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/ripper-ui/app/views/jobs/index.html.erb
<%= render('form', job: @job) if @job.id.nil? %>

<% unless @job.id.nil? %>
<div class="container">
	<table class="table">
		<thead>
			<tr>
			<th>Created At</th>
			<th>Input</th>
			<th>Profiles</th>
			<th>Total Media</th>
			<th>Status</th>
			</tr>
		</thead>
			<tbody>
			<tr class="info">
			<td><%= @job.created_at %></td>
			<td><%= @job.input %></td>
			<td><%= @job.profiles.size %></td>
			<td><%= @job.total_media %></td>
			<td>Processing</td>
			</tr>
		</tbody>
	</table>
  
	<div id="status"></div>
  
  	<div class="actions">
	    <%=
	      button_to 'Cancel', @job, method: :put, data: { confirm: 'Are you sure?' }, class: 'form-control btn-danger'
	    %>
	</div>
</div>

<script type="text/javascript">
  function updateStatus(){
    $.get("/jobs/status/<%= @job.id %>", function(data) {
        $('#status').html(data);

        console.debug($('.progress').text());

        if(/100%/i.test($('.progress').text())){
			window.location.replace("/");
		}

        setTimeout(updateStatus, 10000);
    });
  }
  updateStatus();
</script>
<% end %>

<%= render "list", jobs: @jobs %>	

app/ripper-ui/app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/ripper-ui/app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Input Data:</strong>
  <%= @job.input %>
</p>
<p>
  <strong>Tota Profiles:</strong>
  <%= @job.total_profiles %>
</p>
<p>
  <strong>Total media:</strong>
  <%= @job.done %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/ripper-ui/app/views/jobs/status.html.erb
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="<%= @percent %>" aria-valuemin="0" aria-valuemax="100" style="width:<%= @percent %>%">
   <strong><%= @percent %>%</strong>
  </div>
</div>

app/ripper-ui/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>RipperUi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body> 
    
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


            <a href="/" class="navbar-brand topnav" href="#">Ripper UI</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
            	<li>

            	</li>
                <li>
                    
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Header -->
<a name="about"></a>
<div class="intro-header">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <div style="padding-top: 10px;"></div>
    
                    <%= yield %>
    
                    <br>

                </div>
            </div>

        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.intro-header -->

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <ul class="list-inline">
                    <li>
                        <a href="#">Home</a>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
                <p class="copyright text-muted small">Developed by miniIT - 2016</p>
            </div>
        </div>
    </div>
</footer>
    
    
    
  </body>
</html>

app/ripper-ui/app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :ripped %>
    <%= f.check_box :ripped %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/ripper-ui/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/ripper-ui/app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Ripped</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.username %></td>
        <td><%= profile.ripped %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/ripper-ui/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/ripper-ui/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @profile.username %>
</p>

<p>
  <strong>Ripped:</strong>
  <%= @profile.ripped %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>